server:
  port: 8071

spring:
  datasource:
    username: root
    password: fB8iEcT6RO5EL
    url: jdbc:mysql://39.106.68.246:3306/cpt202?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/

  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /images/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

